{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "rstudio.serviceAccountName" . }}
  labels:
{{ include "rstudio.labels" . | indent 4 }}
{{- end -}}
